const TYPES={char:['getInt8',1],uchar:['getUint8',1],int8:['getInt8',1],uint8:['getUint8',1],short:['getInt16',2],ushort:['getUint16',2],int16:['getInt16',2],uint16:['getUint16',2],int:['getInt32',4],uint:['getUint32',4],int32:['getInt32',4],uint32:['getUint32',4],float:['getFloat32',4],float32:['getFloat32',4],double:['getFloat64',8],float64:['getFloat64',8]};
function headerEnd(bytes){const needle=[101,110,100,95,104,101,97,100,101,114];outer:for(let i=0;i<=bytes.length-needle.length;i++){for(let j=0;j<needle.length;j++)if(bytes[i+j]!==needle[j])continue outer;let p=i+needle.length;while(p<bytes.length&&(bytes[p]===10||bytes[p]===13))p++;return p}throw new Error('Could not find the PLY end_header marker.')}
function schema(text){const lines=text.replace(/\r/g,'').split('\n');let format='',current=null;const elements=[];for(const line of lines){const t=line.trim().split(/\s+/);if(t[0]==='format')format=t[1];else if(t[0]==='element'){current={name:t[1],count:Number(t[2]),properties:[]};elements.push(current)}else if(t[0]==='property'&&current)current.properties.push(t[1]==='list'?{list:true,countType:t[2],type:t[3],name:t[4]}:{list:false,type:t[1],name:t[2]})}const vertex=elements.find(e=>e.name==='vertex'),face=elements.find(e=>e.name==='face');if(!vertex)throw new Error('This PLY file has no vertex element.');return{format,vertex,face,elements}}
function colorValue(value,type){return type==='float'||type==='float32'||type==='double'||type==='float64'?Math.round(Math.max(0,Math.min(1,value))*255):Math.max(0,Math.min(255,value))}
export function parsePly(buffer){const bytes=new Uint8Array(buffer),offset=headerEnd(bytes),head=new TextDecoder('ascii').decode(bytes.subarray(0,offset)),s=schema(head);if(!['ascii','binary_little_endian'].includes(s.format))throw new Error(`Unsupported PLY format: ${s.format}`);return s.format==='ascii'?parseAscii(bytes,offset,s):parseBinary(buffer,offset,s)}
function finish(s,positions,colors,indices){const min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(let i=0;i<positions.length;i+=3)for(let a=0;a<3;a++){min[a]=Math.min(min[a],positions[i+a]);max[a]=Math.max(max[a],positions[i+a])}return{positions,colors,indices,min,max,vertexCount:s.vertex.count,faceCount:s.face?.count||0,triangleCount:indices.length/3,format:s.format}}
function parseAscii(bytes,offset,s){const lines=new TextDecoder('ascii').decode(bytes.subarray(offset)).trim().split(/\r?\n/),positions=new Float32Array(s.vertex.count*3),colors=new Uint8Array(s.vertex.count*3);let line=0;const names=s.vertex.properties.map(p=>p.name),xi=names.indexOf('x'),yi=names.indexOf('y'),zi=names.indexOf('z'),ri=names.indexOf('red'),gi=names.indexOf('green'),bi=names.indexOf('blue');for(let i=0;i<s.vertex.count;i++){const v=lines[line++].trim().split(/\s+/).map(Number);positions.set([v[xi],v[yi],v[zi]],i*3);colors.set(ri>=0?[colorValue(v[ri],s.vertex.properties[ri].type),colorValue(v[gi],s.vertex.properties[gi].type),colorValue(v[bi],s.vertex.properties[bi].type)]:[210,218,228],i*3)}const idx=[];for(let f=0;f<(s.face?.count||0);f++){const v=lines[line++].trim().split(/\s+/).map(Number),n=v[0];for(let j=2;j<n;j++)idx.push(v[1],v[j],v[j+1])}return finish(s,positions,colors,new Uint32Array(idx))}
function parseBinary(buffer,offset,s){const dv=new DataView(buffer);let at=offset;const read=(type)=>{const [fn,size]=TYPES[type]||[];if(!fn)throw new Error(`Unsupported PLY property type: ${type}`);const value=dv[fn](at,true);at+=size;return value};const positions=new Float32Array(s.vertex.count*3),colors=new Uint8Array(s.vertex.count*3);for(const element of s.elements){if(element.name==='vertex'){for(let i=0;i<element.count;i++){let x=0,y=0,z=0,r=210,g=218,b=228;for(const p of element.properties){const value=p.list?(()=>{const n=read(p.countType);for(let k=0;k<n;k++)read(p.type);return 0})():read(p.type);if(p.name==='x')x=value;if(p.name==='y')y=value;if(p.name==='z')z=value;if(p.name==='red')r=colorValue(value,p.type);if(p.name==='green')g=colorValue(value,p.type);if(p.name==='blue')b=colorValue(value,p.type)}positions.set([x,y,z],i*3);colors.set([r,g,b],i*3)}}else if(element.name==='face'){var idx=[];for(let i=0;i<element.count;i++)for(const p of element.properties){if(p.list){const n=read(p.countType),v=[];for(let k=0;k<n;k++)v.push(read(p.type));if(p.name==='vertex_indices'||p.name==='vertex_index')for(let j=1;j<n-1;j++)idx.push(v[0],v[j],v[j+1])}else read(p.type)}}else{for(let i=0;i<element.count;i++)for(const p of element.properties){if(p.list){const n=read(p.countType);for(let k=0;k<n;k++)read(p.type)}else read(p.type)}}}return finish(s,positions,colors,new Uint32Array(idx||[]))}
export function sampleVertices(model,limit){const count=Math.min(model.vertexCount,Math.max(1,limit)),positions=new model.positions.constructor(count*3),colors=new Uint8Array(count*3),stride=model.vertexCount/count;for(let i=0;i<count;i++){const source=Math.min(model.vertexCount-1,Math.floor(i*stride));positions.set(model.positions.subarray(source*3,source*3+3),i*3);colors.set(model.colors.subarray(source*3,source*3+3),i*3)}return{positions,colors,count}}

export function createGridBoxGeometry(divisions=12,halfSize=6){const positions=[],colors=[],line=(...values)=>{positions.push(...values);colors.push(80,94,108,80,94,108)};for(let i=-divisions;i<=divisions;i++){const offset=i/divisions*halfSize;line(-halfSize,offset,-halfSize,halfSize,offset,-halfSize);line(offset,-halfSize,-halfSize,offset,halfSize,-halfSize);line(-halfSize,offset,halfSize,halfSize,offset,halfSize);line(offset,-halfSize,halfSize,offset,halfSize,halfSize);line(-halfSize,-halfSize,offset,-halfSize,halfSize,offset);line(-halfSize,offset,-halfSize,-halfSize,offset,halfSize);line(halfSize,-halfSize,offset,halfSize,halfSize,offset);line(halfSize,offset,-halfSize,halfSize,offset,halfSize);line(-halfSize,-halfSize,offset,halfSize,-halfSize,offset);line(offset,-halfSize,-halfSize,offset,-halfSize,halfSize);line(-halfSize,halfSize,offset,halfSize,halfSize,offset);line(offset,halfSize,-halfSize,offset,halfSize,halfSize)}return{positions:new Float32Array(positions),colors:new Uint8Array(colors),count:positions.length/3}}

export function createWireframeIndices(indices){const edges=new Uint32Array(indices.length*2);for(let i=0,o=0;i<indices.length;i+=3){const a=indices[i],b=indices[i+1],c=indices[i+2];edges.set([a,b,b,c,c,a],o);o+=6}return edges}

export function centerAndMapZUp(positions,min,max){const out=new Float32Array(positions.length),center=min.map((value,index)=>(value+max[index])/2),radius=Math.max(...max.map((value,index)=>value-min[index]))||1;for(let i=0;i<positions.length;i+=3){out[i]=(positions[i]-center[0])/radius;out[i+1]=(positions[i+2]-center[2])/radius;out[i+2]=-(positions[i+1]-center[1])/radius}return out}
