import{centerAndMapZUp,createGridBoxGeometry,createWireframeIndices,sampleVertices}from'./ply.js';
import{formatBBoxDimensions,VIEW_ANGLES}from'./view-utils.js';
const $=id=>document.getElementById(id);$('app-version').textContent=`v${__APP_VERSION__}`;const canvas=$('viewport'),gl=canvas.getContext('webgl2',{antialias:true});if(!gl)throw new Error('This viewer requires a browser with WebGL 2 support.');
const vs=`#version 300 es\nin vec3 p;in vec3 c;uniform mat4 mvp;uniform float size;out vec3 color;void main(){gl_Position=mvp*vec4(p,1);gl_PointSize=size;color=c/255.;}`,fs=`#version 300 es\nprecision mediump float;in vec3 color;uniform float alpha;out vec4 outColor;void main(){outColor=vec4(color,alpha);}`;
function shader(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s}const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vs));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(program);const loc={p:gl.getAttribLocation(program,'p'),c:gl.getAttribLocation(program,'c'),mvp:gl.getUniformLocation(program,'mvp'),size:gl.getUniformLocation(program,'size'),alpha:gl.getUniformLocation(program,'alpha')};
const BOX_HALF_SIZE=6,CAMERA_LIMIT=5.5;let model=null,points=null,[yaw,pitch]=VIEW_ANGLES.ISO,distance=3,pan=[0,0],drag=null,last=[0,0],light=false,buffers={};
const mat={identity:()=>new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]),mul:(a,b)=>{const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o},perspective:(f,a,n,z)=>{const t=1/Math.tan(f/2),o=new Float32Array(16);o[0]=t/a;o[5]=t;o[10]=(z+n)/(n-z);o[11]=-1;o[14]=2*z*n/(n-z);return o},translate:(x,y,z)=>{const o=mat.identity();o[12]=x;o[13]=y;o[14]=z;return o},rx:a=>{const o=mat.identity(),c=Math.cos(a),s=Math.sin(a);o[5]=c;o[6]=s;o[9]=-s;o[10]=c;return o},ry:a=>{const o=mat.identity(),c=Math.cos(a),s=Math.sin(a);o[0]=c;o[2]=-s;o[8]=s;o[10]=c;return o}};
function upload(name,data,kind=gl.ARRAY_BUFFER){if(buffers[name])gl.deleteBuffer(buffers[name]);const b=gl.createBuffer();gl.bindBuffer(kind,b);gl.bufferData(kind,data,gl.STATIC_DRAW);buffers[name]=b;return b}function bind(pos,col){gl.bindBuffer(gl.ARRAY_BUFFER,pos);gl.enableVertexAttribArray(loc.p);gl.vertexAttribPointer(loc.p,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,col);gl.enableVertexAttribArray(loc.c);gl.vertexAttribPointer(loc.c,3,gl.UNSIGNED_BYTE,false,0,0)}
function rebuild(){if(!model)return;points=sampleVertices(model,Number($('point-limit').value));upload('pointP',centered(points.positions));upload('pointC',points.colors);$('displayed').textContent=points.count.toLocaleString();requestAnimationFrame(render)}function centered(src){return centerAndMapZUp(src,model.min,model.max)}
function grid(){const geometry=createGridBoxGeometry(12,BOX_HALF_SIZE);upload('gridP',geometry.positions);upload('gridC',geometry.colors);buffers.gridCount=geometry.count}grid();
function bboxData(){const s=model.max.map((v,i)=>v-model.min[i]),r=Math.max(...s)||1,mn=s.map(v=>-v/(2*r)),mx=s.map(v=>v/(2*r)),source=[[mn[0],mn[1],mn[2]],[mx[0],mn[1],mn[2]],[mx[0],mx[1],mn[2]],[mn[0],mx[1],mn[2]],[mn[0],mn[1],mx[2]],[mx[0],mn[1],mx[2]],[mx[0],mx[1],mx[2]],[mn[0],mx[1],mx[2]]],corners=source.map(([x,y,z])=>[x,z,-y]),edges=[0,1,1,2,2,3,3,0,4,5,5,6,6,7,7,4,0,4,1,5,2,6,3,7],a=[];for(const i of edges)a.push(...corners[i]);upload('bboxP',new Float32Array(a));upload('bboxC',new Uint8Array(edges.flatMap(()=>[73,166,255])));buffers.bboxCount=edges.length}
function render(){canvas.width=Math.round(canvas.clientWidth*devicePixelRatio);canvas.height=Math.round(canvas.clientHeight*devicePixelRatio);gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(...(light?[.91,.94,.97,1]:[.035,.05,.07,1]));gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.useProgram(program);let view=mat.mul(mat.translate(pan[0],pan[1],-distance),mat.mul(mat.rx(pitch),mat.ry(yaw))),mvp=mat.mul(mat.perspective(.8,canvas.width/canvas.height,.01,100),view);gl.uniformMatrix4fv(loc.mvp,false,mvp);gl.uniform1f(loc.size,Number($('point-size').value)*devicePixelRatio);const draw=(p,c,mode,count,alpha=1)=>{bind(p,c);gl.uniform1f(loc.alpha,alpha);gl.drawArrays(mode,0,count)};if($('show-grid').checked)draw(buffers.gridP,buffers.gridC,gl.LINES,buffers.gridCount);if(model){if($('show-mesh').checked&&model.indices.length){gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);bind(buffers.meshP,buffers.meshC);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,buffers.index);gl.enable(gl.POLYGON_OFFSET_FILL);gl.polygonOffset(1,1);gl.uniform1f(loc.alpha,Number($('mesh-opacity').value)/100);gl.drawElements(gl.TRIANGLES,model.indices.length,gl.UNSIGNED_INT,0);gl.disable(gl.POLYGON_OFFSET_FILL);gl.disable(gl.BLEND)}if($('show-wireframe').checked&&buffers.wireIndex){bind(buffers.meshP,buffers.meshC);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,buffers.wireIndex);gl.uniform1f(loc.alpha,1);gl.drawElements(gl.LINES,buffers.wireCount,gl.UNSIGNED_INT,0)}if($('show-points').checked)draw(buffers.pointP,buffers.pointC,gl.POINTS,points.count);if($('show-bbox').checked)draw(buffers.bboxP,buffers.bboxC,gl.LINES,buffers.bboxCount)}drawAxis()}
const dropOverlay=$('drop-overlay'),loadingOverlay=$('loading-overlay'),progress=$('loading-progress'),loadingPercent=$('loading-percent'),loadingStage=$('loading-stage');
let activeLoad=null,dragDepth=0;
class LoadCancelled extends Error{constructor(){super('Loading cancelled');this.name='LoadCancelled'}}
function setProgress(value,label,indeterminate=false){loadingStage.textContent=label;progress.classList.toggle('indeterminate',indeterminate);if(!indeterminate){const percent=Math.max(0,Math.min(100,Math.round(value)));progress.style.width=`${percent}%`;loadingPercent.value=`${percent}%`}else{progress.style.width='36%';loadingPercent.value='Processing…'}}
function beginLoad(name){if(activeLoad)cancelLoad();const token={cancelled:false,worker:null,reader:null,name};activeLoad=token;loadingOverlay.hidden=false;requestAnimationFrame(()=>loadingOverlay.classList.add('visible'));dropOverlay.classList.remove('visible');document.body.setAttribute('aria-busy','true');setProgress(0,'Reading file');$('status').textContent=`${name}  is loading…`;return token}
function finishLoad(token){if(activeLoad!==token)return;loadingOverlay.classList.remove('visible');loadingOverlay.hidden=true;document.body.removeAttribute('aria-busy');activeLoad=null}
function cancelLoad(){const token=activeLoad;if(!token)return;token.cancelled=true;token.worker?.terminate();token.reader?.cancel().catch(()=>{});finishLoad(token);$('status').textContent='Loading cancelled'}
async function readWebFile(file,token){if(!file.stream){setProgress(5,'Reading file',true);const buffer=await file.arrayBuffer();if(token.cancelled)throw new LoadCancelled();return buffer}const reader=file.stream().getReader(),chunks=[];token.reader=reader;let received=0;while(true){if(token.cancelled)throw new LoadCancelled();const{done,value}=await reader.read();if(done)break;chunks.push(value);received+=value.byteLength;setProgress(file.size?received/file.size*65:5,'Reading file',!file.size)}const bytes=new Uint8Array(received);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength}return bytes.buffer}
function parseInWorker(buffer,token){return new Promise((resolve,reject)=>{if(token.cancelled)return reject(new LoadCancelled());const worker=new Worker(new URL('./ply-worker.js',import.meta.url),{type:'module'});token.worker=worker;worker.onmessage=event=>{worker.terminate();token.worker=null;if(token.cancelled)return reject(new LoadCancelled());event.data?.error?reject(new Error(event.data.error)):resolve(event.data)};worker.onerror=event=>{worker.terminate();token.worker=null;reject(new Error(event.message||'Failed to parse the PLY file'))};worker.postMessage(buffer,[buffer])})}
function applyModel(name,size,nextModel){model=nextModel;upload('meshP',centered(model.positions));upload('meshC',model.colors);upload('index',model.indices,gl.ELEMENT_ARRAY_BUFFER);const wireIndices=createWireframeIndices(model.indices);upload('wireIndex',wireIndices,gl.ELEMENT_ARRAY_BUFFER);buffers.wireCount=wireIndices.length;bboxData();rebuild();const center=model.min.map((v,i)=>(v+model.max[i])/2),localMin=model.min.map((v,i)=>v-center[i]),localMax=model.max.map((v,i)=>v-center[i]);const isMesh=model.indices.length>0;$('mesh-controls').hidden=!isMesh;$('point-controls').hidden=isMesh;$('file-name').textContent=name;$('kind').textContent=isMesh?'Mesh':'Point cloud';$('vertices').textContent=model.vertexCount.toLocaleString();$('triangles').textContent=model.triangleCount.toLocaleString();$('file-size').textContent=formatBytes(size);$('global-bbox').textContent=formatBBoxDimensions(model.min,model.max);$('local-bbox').textContent=formatBBoxDimensions(localMin,localMax);$('drop-zone').classList.add('hidden');$('status').textContent=`${model.format} · loaded`;fit()}
async function loadBuffer(name,size,buffer,token=beginLoad(name)){try{if(token.cancelled)throw new LoadCancelled();setProgress(70,'Parsing PLY structure',true);const parsed=await parseInWorker(buffer,token);if(token.cancelled)throw new LoadCancelled();setProgress(92,'Uploading to GPU');await new Promise(requestAnimationFrame);applyModel(name,size,parsed);setProgress(100,'Complete')}catch(error){if(!(error instanceof LoadCancelled)){console.error(error);$('status').textContent=error.message||String(error);if(!model)$('drop-zone').classList.remove('hidden')}}finally{finishLoad(token)}}
async function openFile(file){if(!file?.name.toLowerCase().endsWith('.ply')){$('status').textContent='Only PLY files can be opened';return}const token=beginLoad(file.name);try{const buffer=await readWebFile(file,token);await loadBuffer(file.name,file.size,buffer,token)}catch(error){if(!(error instanceof LoadCancelled)){console.error(error);$('status').textContent=error.message||String(error)}finishLoad(token)}}function formatBytes(n){const u=['B','KB','MB','GB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return`${n.toFixed(i?1:0)} ${u[i]}`}
function fit(){distance=2.1;pan=[0,0];requestAnimationFrame(render)}function setView(view){[yaw,pitch]=VIEW_ANGLES[view];document.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===view));render()}document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>setView(button.dataset.view));$('fit-view').onclick=fit;
const dz=$('drop-zone'),input=$('file-input'),choose=()=>{if(!activeLoad)input.click()};dz.onclick=choose;dz.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose()}};input.onchange=()=>{openFile(input.files[0]);input.value=''};
function hasFiles(event){return Array.from(event.dataTransfer?.types||[]).includes('Files')}
addEventListener('dragenter',event=>{if(!hasFiles(event))return;event.preventDefault();dragDepth++;dropOverlay.classList.add('visible');dropOverlay.setAttribute('aria-hidden','false')});addEventListener('dragover',event=>{if(hasFiles(event))event.preventDefault()});addEventListener('dragleave',event=>{if(!hasFiles(event))return;event.preventDefault();dragDepth=Math.max(0,dragDepth-1);if(!dragDepth){dropOverlay.classList.remove('visible');dropOverlay.setAttribute('aria-hidden','true')}});addEventListener('drop',event=>{event.preventDefault();dragDepth=0;dropOverlay.classList.remove('visible');dropOverlay.setAttribute('aria-hidden','true');if(event.dataTransfer.files.length)openFile(event.dataTransfer.files[0])});
$('cancel-load').onclick=cancelLoad;const VIEW_KEYS={w:'+Z',s:'-Z',a:'-X',d:'+X',q:'-Y',e:'+Y'};addEventListener('keydown',event=>{if(event.key==='Escape'&&activeLoad){event.preventDefault();cancelLoad();return}if(activeLoad||event.ctrlKey||event.metaKey||event.altKey||/^(INPUT|BUTTON)$/.test(event.target.tagName))return;const view=VIEW_KEYS[event.key.toLowerCase()];if(view){event.preventDefault();setView(view)}});
function constrainCamera(){const panLength=Math.hypot(...pan),maxPan=CAMERA_LIMIT-.25;if(panLength>maxPan)pan=pan.map(value=>value*maxPan/panLength);distance=Math.max(.15,Math.min(Math.sqrt(Math.max(.15,CAMERA_LIMIT**2-Math.hypot(...pan)**2)),distance))}canvas.onpointerdown=e=>{drag=e.button;last=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId)};canvas.onpointerup=()=>drag=null;canvas.onpointermove=e=>{if(drag===null)return;const dx=e.clientX-last[0],dy=e.clientY-last[1];last=[e.clientX,e.clientY];if(drag===0){yaw+=dx*.008;pitch=Math.max(-1.55,Math.min(1.55,pitch+dy*.008))}else if(drag===2){pan[0]+=dx/canvas.clientHeight*distance;pan[1]-=dy/canvas.clientHeight*distance;constrainCamera()}render()};canvas.oncontextmenu=e=>e.preventDefault();canvas.onwheel=e=>{e.preventDefault();distance*=Math.exp(e.deltaY*.001);constrainCamera();render()};
$('point-size').oninput=e=>{$('point-size-value').value=`${e.target.value} px`;render()};$('point-limit').oninput=e=>$('point-limit-value').value=Number(e.target.value).toLocaleString();$('point-limit').onchange=rebuild;for(const id of['show-mesh','show-wireframe','show-points','show-grid','show-bbox'])$(id).onchange=render;$('mesh-opacity').oninput=e=>{$('mesh-opacity-value').value=`${e.target.value}%`;render()};$('theme').onclick=()=>{light=!light;document.body.classList.toggle('light',light);render()};addEventListener('resize',render);
let axisTargets=[];function drawAxis(){const a=$('axis'),x=a.getContext('2d'),w=a.width,h=a.height;x.clearRect(0,0,w,h);const rot=(v)=>{let[xv,yv,zv]=v,c=Math.cos(yaw),s=Math.sin(yaw);[xv,zv]=[c*xv+s*zv,-s*xv+c*zv];c=Math.cos(pitch);s=Math.sin(pitch);[yv,zv]=[c*yv-s*zv,s*yv+c*zv];return[xv,yv,zv]},axes=[[[1,0,0],'#ef5350','X','+X'],[[0,0,-1],'#66bb6a','Y','+Y'],[[0,1,0],'#42a5f5','Z','+Z']].map(([v,color,label,view])=>[rot(v),color,label,view]).sort((a,b)=>a[0][2]-b[0][2]);axisTargets=[];x.lineWidth=3;x.font='bold 13px "Noto Sans",system-ui';x.textAlign='center';x.textBaseline='middle';for(const[v,color,label,view]of axes){const ex=w/2+v[0]*34,ey=h/2-v[1]*34;axisTargets.push({x:ex,y:ey,view});x.strokeStyle=color;x.fillStyle=color;x.beginPath();x.moveTo(w/2,h/2);x.lineTo(ex,ey);x.stroke();x.beginPath();x.arc(ex,ey,10,0,Math.PI*2);x.fill();x.fillStyle='#fff';x.fillText(label,ex,ey)}}const axisCanvas=$('axis');axisCanvas.onclick=event=>{if(activeLoad)return;const rect=axisCanvas.getBoundingClientRect(),scaleX=axisCanvas.width/rect.width,scaleY=axisCanvas.height/rect.height,x=(event.clientX-rect.left)*scaleX,y=(event.clientY-rect.top)*scaleY,target=axisTargets.reduce((best,item)=>Math.hypot(item.x-x,item.y-y)<Math.hypot(best.x-x,best.y-y)?item:best,axisTargets[0]);if(target&&Math.hypot(target.x-x,target.y-y)<=18)setView(target.view)};render();
