import{centerAndMapZUp,createGridBoxGeometry,createWireframeIndices,sampleVertices}from'./ply.js';
import{formatBBoxDimensions,VIEW_ANGLES}from'./view-utils.js';
import{multiplyQuaternions,projectToTrackball,quaternionBetweenVectors,quaternionFromViewAngles,quaternionToMatrix,viewAnglesFromQuaternion}from'./trackball.js';
import{createPreviewCubeGeometry,interpolateMatrices}from'./viewport-utils.js';

const $=id=>document.getElementById(id);$('app-version').textContent=`v${__APP_VERSION__}`;
const canvas=$('viewport'),gl=canvas.getContext('webgl2',{antialias:true});if(!gl)throw new Error('This viewer requires a browser with WebGL 2 support.');
const sceneVS=`#version 300 es
in vec3 p;in vec3 c;uniform mat4 mvp;uniform float size;out vec3 color;void main(){gl_Position=mvp*vec4(p,1);gl_PointSize=size;color=c/255.;}`;
const sceneFS=`#version 300 es
precision mediump float;in vec3 color;uniform float alpha;out vec4 outColor;void main(){outColor=vec4(color,alpha);}`;
const normalVS=`#version 300 es
in vec3 p;uniform mat4 mvp;uniform mat4 modelView;out vec3 viewPosition;void main(){vec4 view=modelView*vec4(p,1);viewPosition=view.xyz;gl_Position=mvp*vec4(p,1);}`;
const normalFS=`#version 300 es
precision highp float;in vec3 viewPosition;out vec4 outNormal;void main(){vec3 normal=normalize(cross(dFdx(viewPosition),dFdy(viewPosition)));outNormal=vec4(normal*.5+.5,1);}`;
const edgeVS=`#version 300 es
const vec2 points[3]=vec2[3](vec2(-1,-1),vec2(3,-1),vec2(-1,3));out vec2 uv;void main(){vec2 point=points[gl_VertexID];uv=point*.5+.5;gl_Position=vec4(point,0,1);}`;
const edgeFS=`#version 300 es
precision highp float;in vec2 uv;uniform sampler2D depthTexture;uniform sampler2D normalTexture;uniform vec2 texel;uniform vec3 edgeColor;out vec4 outColor;void main(){float centerDepth=texture(depthTexture,uv).r;if(centerDepth>=.999999)discard;vec3 centerNormal=texture(normalTexture,uv).rgb;float depthEdge=0.;float normalEdge=0.;for(int x=-1;x<=1;x++){for(int y=-1;y<=1;y++){if(x==0&&y==0)continue;vec2 offset=vec2(float(x),float(y))*texel;float sampleDepth=texture(depthTexture,uv+offset).r;vec3 sampleNormal=texture(normalTexture,uv+offset).rgb;depthEdge=max(depthEdge,abs(centerDepth-sampleDepth));normalEdge=max(normalEdge,length(centerNormal-sampleNormal));}}float edge=max(smoothstep(.00008,.0012,depthEdge),smoothstep(.12,.34,normalEdge));if(edge<.01)discard;outColor=vec4(edgeColor,edge*.78);}`;
function shader(type,source){const result=gl.createShader(type);gl.shaderSource(result,source);gl.compileShader(result);if(!gl.getShaderParameter(result,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(result));return result}
function makeProgram(vertex,fragment){const result=gl.createProgram();gl.attachShader(result,shader(gl.VERTEX_SHADER,vertex));gl.attachShader(result,shader(gl.FRAGMENT_SHADER,fragment));gl.linkProgram(result);if(!gl.getProgramParameter(result,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(result));return result}
const sceneProgram=makeProgram(sceneVS,sceneFS),normalProgram=makeProgram(normalVS,normalFS),edgeProgram=makeProgram(edgeVS,edgeFS);
const sceneLoc={p:gl.getAttribLocation(sceneProgram,'p'),c:gl.getAttribLocation(sceneProgram,'c'),mvp:gl.getUniformLocation(sceneProgram,'mvp'),size:gl.getUniformLocation(sceneProgram,'size'),alpha:gl.getUniformLocation(sceneProgram,'alpha')},normalLoc={p:gl.getAttribLocation(normalProgram,'p'),mvp:gl.getUniformLocation(normalProgram,'mvp'),modelView:gl.getUniformLocation(normalProgram,'modelView')},edgeLoc={depth:gl.getUniformLocation(edgeProgram,'depthTexture'),normal:gl.getUniformLocation(edgeProgram,'normalTexture'),texel:gl.getUniformLocation(edgeProgram,'texel'),color:gl.getUniformLocation(edgeProgram,'edgeColor')};

const BOX_HALF_SIZE=6,CAMERA_LIMIT=5.5,VIEW_TRANSITION_MS=300;
let model=null,points=null,[yaw,pitch]=VIEW_ANGLES.ISO,viewQuaternion=quaternionFromViewAngles(yaw,pitch),arcballStart=null,arcballBase=null,distance=3,pan=[0,0],drag=null,last=[0,0],light=false,buffers={};
let viewTransition=null,viewTransitionFrame=null,previewOrbiting=true,previewFrame=null,previewStarted=performance.now();
const mat={identity:()=>new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]),mul:(a,b)=>{const out=new Float32Array(16);for(let column=0;column<4;column++)for(let row=0;row<4;row++)for(let index=0;index<4;index++)out[column*4+row]+=a[index*4+row]*b[column*4+index];return out},perspective:(fieldOfView,aspect,near,far)=>{const factor=1/Math.tan(fieldOfView/2),out=new Float32Array(16);out[0]=factor/aspect;out[5]=factor;out[10]=(far+near)/(near-far);out[11]=-1;out[14]=2*far*near/(near-far);return out},translate:(x,y,z)=>{const out=mat.identity();out[12]=x;out[13]=y;out[14]=z;return out},rx:angle=>{const out=mat.identity(),cos=Math.cos(angle),sin=Math.sin(angle);out[5]=cos;out[6]=sin;out[9]=-sin;out[10]=cos;return out},ry:angle=>{const out=mat.identity(),cos=Math.cos(angle),sin=Math.sin(angle);out[0]=cos;out[2]=-sin;out[8]=sin;out[10]=cos;return out}};
function baseRotation(){return $('trackball-rotation').checked?quaternionToMatrix(viewQuaternion):mat.mul(mat.rx(pitch),mat.ry(yaw))}function viewRotation(){return viewTransition?.matrix||baseRotation()}
function upload(name,data,kind=gl.ARRAY_BUFFER){if(buffers[name])gl.deleteBuffer(buffers[name]);const buffer=gl.createBuffer();gl.bindBuffer(kind,buffer);gl.bufferData(kind,data,gl.STATIC_DRAW);buffers[name]=buffer;return buffer}
function bindScene(position,color){gl.bindBuffer(gl.ARRAY_BUFFER,position);gl.enableVertexAttribArray(sceneLoc.p);gl.vertexAttribPointer(sceneLoc.p,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,color);gl.enableVertexAttribArray(sceneLoc.c);gl.vertexAttribPointer(sceneLoc.c,3,gl.UNSIGNED_BYTE,false,0,0)}
function initializeGeometry(){const grid=createGridBoxGeometry(12,BOX_HALF_SIZE);upload('gridP',grid.positions);upload('gridC',grid.colors);buffers.gridCount=grid.count;const cube=createPreviewCubeGeometry();upload('previewP',cube.positions);upload('previewC',cube.colors);upload('previewIndex',cube.indices,gl.ELEMENT_ARRAY_BUFFER);buffers.previewCount=cube.indices.length}initializeGeometry();
function centered(source){return centerAndMapZUp(source,model.min,model.max)}function rebuild(){if(!model)return;points=sampleVertices(model,Number($('point-limit').value));upload('pointP',centered(points.positions));upload('pointC',points.colors);$('displayed').textContent=points.count.toLocaleString();requestAnimationFrame(render)}
function bboxData(){const size=model.max.map((value,index)=>value-model.min[index]),radius=Math.max(...size)||1,min=size.map(value=>-value/(2*radius)),max=size.map(value=>value/(2*radius)),source=[[min[0],min[1],min[2]],[max[0],min[1],min[2]],[max[0],max[1],min[2]],[min[0],max[1],min[2]],[min[0],min[1],max[2]],[max[0],min[1],max[2]],[max[0],max[1],max[2]],[min[0],max[1],max[2]]],corners=source.map(([x,y,z])=>[x,z,-y]),edges=[0,1,1,2,2,3,3,0,4,5,5,6,6,7,7,4,0,4,1,5,2,6,3,7],positions=[];for(const index of edges)positions.push(...corners[index]);upload('bboxP',new Float32Array(positions));upload('bboxC',new Uint8Array(edges.flatMap(()=>[73,166,255])));buffers.bboxCount=edges.length}

const edgeTarget={framebuffer:gl.createFramebuffer(),normal:gl.createTexture(),depth:gl.createTexture(),width:0,height:0};
function resizeEdgeTarget(width,height){if(edgeTarget.width===width&&edgeTarget.height===height)return;edgeTarget.width=width;edgeTarget.height=height;gl.bindTexture(gl.TEXTURE_2D,edgeTarget.normal);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA8,width,height,0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.bindTexture(gl.TEXTURE_2D,edgeTarget.depth);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texImage2D(gl.TEXTURE_2D,0,gl.DEPTH_COMPONENT24,width,height,0,gl.DEPTH_COMPONENT,gl.UNSIGNED_INT,null);gl.bindFramebuffer(gl.FRAMEBUFFER,edgeTarget.framebuffer);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,edgeTarget.normal,0);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.TEXTURE_2D,edgeTarget.depth,0);gl.bindFramebuffer(gl.FRAMEBUFFER,null)}
function surface(){if(!model)return{position:buffers.previewP,index:buffers.previewIndex,count:buffers.previewCount};if($('show-mesh').checked&&model.indices.length)return{position:buffers.meshP,index:buffers.index,count:model.indices.length};return null}
function renderEdgePrepass(mvp,view){const mesh=surface();if(!$('edge-enhancement').checked||!mesh)return false;resizeEdgeTarget(canvas.width,canvas.height);gl.bindFramebuffer(gl.FRAMEBUFFER,edgeTarget.framebuffer);gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.disable(gl.BLEND);gl.useProgram(normalProgram);gl.bindBuffer(gl.ARRAY_BUFFER,mesh.position);gl.enableVertexAttribArray(normalLoc.p);gl.vertexAttribPointer(normalLoc.p,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,mesh.index);gl.uniformMatrix4fv(normalLoc.mvp,false,mvp);gl.uniformMatrix4fv(normalLoc.modelView,false,view);gl.drawElements(gl.TRIANGLES,mesh.count,gl.UNSIGNED_INT,0);gl.bindFramebuffer(gl.FRAMEBUFFER,null);return true}
function compositeEdges(){gl.disable(gl.DEPTH_TEST);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.useProgram(edgeProgram);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,edgeTarget.depth);gl.uniform1i(edgeLoc.depth,0);gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,edgeTarget.normal);gl.uniform1i(edgeLoc.normal,1);gl.uniform2f(edgeLoc.texel,1/canvas.width,1/canvas.height);gl.uniform3f(edgeLoc.color,...(light?[.03,.05,.07]:[.72,.8,.9]));gl.drawArrays(gl.TRIANGLES,0,3);gl.disable(gl.BLEND)}
function render(){canvas.width=Math.max(1,Math.round(canvas.clientWidth*devicePixelRatio));canvas.height=Math.max(1,Math.round(canvas.clientHeight*devicePixelRatio));const rotation=viewRotation(),view=mat.mul(mat.translate(pan[0],pan[1],-distance),rotation),projection=mat.perspective(.8,canvas.width/canvas.height,.01,100),mvp=mat.mul(projection,view),hasEdges=renderEdgePrepass(mvp,view);gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(...(light?[.91,.94,.97,1]:[.035,.05,.07,1]));gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.useProgram(sceneProgram);gl.uniformMatrix4fv(sceneLoc.mvp,false,mvp);gl.uniform1f(sceneLoc.size,Number($('point-size').value)*devicePixelRatio);const draw=(position,color,mode,count,alpha=1)=>{bindScene(position,color);gl.uniform1f(sceneLoc.alpha,alpha);gl.drawArrays(mode,0,count)};if($('show-grid').checked)draw(buffers.gridP,buffers.gridC,gl.LINES,buffers.gridCount);if(!model){bindScene(buffers.previewP,buffers.previewC);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,buffers.previewIndex);gl.uniform1f(sceneLoc.alpha,1);gl.drawElements(gl.TRIANGLES,buffers.previewCount,gl.UNSIGNED_INT,0)}else{if($('show-mesh').checked&&model.indices.length){const alpha=Number($('mesh-opacity').value)/100;if(alpha<1){gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA)}bindScene(buffers.meshP,buffers.meshC);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,buffers.index);gl.enable(gl.POLYGON_OFFSET_FILL);gl.polygonOffset(1,1);gl.uniform1f(sceneLoc.alpha,alpha);gl.drawElements(gl.TRIANGLES,model.indices.length,gl.UNSIGNED_INT,0);gl.disable(gl.POLYGON_OFFSET_FILL);gl.disable(gl.BLEND)}if($('show-wireframe').checked&&buffers.wireIndex){bindScene(buffers.meshP,buffers.meshC);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,buffers.wireIndex);gl.uniform1f(sceneLoc.alpha,1);gl.drawElements(gl.LINES,buffers.wireCount,gl.UNSIGNED_INT,0)}if($('show-points').checked)draw(buffers.pointP,buffers.pointC,gl.POINTS,points.count);if($('show-bbox').checked)draw(buffers.bboxP,buffers.bboxC,gl.LINES,buffers.bboxCount)}if(hasEdges)compositeEdges();drawAxis()}

const dropOverlay=$('drop-overlay'),loadingOverlay=$('loading-overlay'),progress=$('loading-progress'),loadingPercent=$('loading-percent'),loadingStage=$('loading-stage');let activeLoad=null,dragDepth=0;
class LoadCancelled extends Error{constructor(){super('Loading cancelled');this.name='LoadCancelled'}}
function setProgress(value,label,indeterminate=false){loadingStage.textContent=label;progress.classList.toggle('indeterminate',indeterminate);if(!indeterminate){const percent=Math.max(0,Math.min(100,Math.round(value)));progress.style.width=`${percent}%`;loadingPercent.value=`${percent}%`}else{progress.style.width='36%';loadingPercent.value='Processing…'}}
function beginLoad(name){if(activeLoad)cancelLoad();const token={cancelled:false,worker:null,reader:null,name};activeLoad=token;loadingOverlay.hidden=false;requestAnimationFrame(()=>loadingOverlay.classList.add('visible'));dropOverlay.classList.remove('visible');document.body.setAttribute('aria-busy','true');setProgress(0,'Reading file');$('status').textContent=`${name} is loading…`;return token}function finishLoad(token){if(activeLoad!==token)return;loadingOverlay.classList.remove('visible');loadingOverlay.hidden=true;document.body.removeAttribute('aria-busy');activeLoad=null}function cancelLoad(){const token=activeLoad;if(!token)return;token.cancelled=true;token.worker?.terminate();token.reader?.cancel().catch(()=>{});finishLoad(token);$('status').textContent='Loading cancelled'}
async function readWebFile(file,token){if(!file.stream){setProgress(5,'Reading file',true);const buffer=await file.arrayBuffer();if(token.cancelled)throw new LoadCancelled();return buffer}const reader=file.stream().getReader(),chunks=[];token.reader=reader;let received=0;while(true){if(token.cancelled)throw new LoadCancelled();const{done,value}=await reader.read();if(done)break;chunks.push(value);received+=value.byteLength;setProgress(file.size?received/file.size*65:5,'Reading file',!file.size)}const bytes=new Uint8Array(received);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength}return bytes.buffer}
function parseInWorker(buffer,token){return new Promise((resolve,reject)=>{if(token.cancelled)return reject(new LoadCancelled());const worker=new Worker(new URL('./ply-worker.js',import.meta.url),{type:'module'});token.worker=worker;worker.onmessage=event=>{worker.terminate();token.worker=null;if(token.cancelled)return reject(new LoadCancelled());event.data?.error?reject(new Error(event.data.error)):resolve(event.data)};worker.onerror=event=>{worker.terminate();token.worker=null;reject(new Error(event.message||'Failed to parse the PLY file'))};worker.postMessage(buffer,[buffer])})}
function applyModel(name,size,nextModel){model=nextModel;upload('meshP',centered(model.positions));upload('meshC',model.colors);upload('index',model.indices,gl.ELEMENT_ARRAY_BUFFER);const wireIndices=createWireframeIndices(model.indices);upload('wireIndex',wireIndices,gl.ELEMENT_ARRAY_BUFFER);buffers.wireCount=wireIndices.length;bboxData();rebuild();const center=model.min.map((value,index)=>(value+model.max[index])/2),localMin=model.min.map((value,index)=>value-center[index]),localMax=model.max.map((value,index)=>value-center[index]),isMesh=model.indices.length>0;$('mesh-controls').hidden=!isMesh;$('point-controls').hidden=isMesh;$('file-name').textContent=name;$('kind').textContent=isMesh?'Mesh':'Point cloud';$('vertices').textContent=model.vertexCount.toLocaleString();$('triangles').textContent=model.triangleCount.toLocaleString();$('file-size').textContent=formatBytes(size);$('global-bbox').textContent=formatBBoxDimensions(model.min,model.max);$('local-bbox').textContent=formatBBoxDimensions(localMin,localMax);$('drop-zone').classList.add('hidden');$('status').textContent=`${model.format} · loaded`;fit()}
async function loadBuffer(name,size,buffer,token=beginLoad(name)){try{if(token.cancelled)throw new LoadCancelled();setProgress(70,'Parsing PLY structure',true);const parsed=await parseInWorker(buffer,token);if(token.cancelled)throw new LoadCancelled();setProgress(92,'Uploading to GPU');await new Promise(requestAnimationFrame);applyModel(name,size,parsed);setProgress(100,'Complete')}catch(error){if(!(error instanceof LoadCancelled)){console.error(error);$('status').textContent=error.message||String(error);if(!model)$('drop-zone').classList.remove('hidden')}}finally{finishLoad(token)}}
async function openFile(file){if(!file?.name.toLowerCase().endsWith('.ply')){$('status').textContent='Only PLY files can be opened';return}const token=beginLoad(file.name);try{const buffer=await readWebFile(file,token);await loadBuffer(file.name,file.size,buffer,token)}catch(error){if(!(error instanceof LoadCancelled)){console.error(error);$('status').textContent=error.message||String(error)}finishLoad(token)}}function formatBytes(value){const units=['B','KB','MB','GB'];let index=0;while(value>=1024&&index<units.length-1){value/=1024;index++}return`${value.toFixed(index?1:0)} ${units[index]}`}

function stopPreviewOrbit(){if(!previewOrbiting)return;previewOrbiting=false;if(previewFrame)cancelAnimationFrame(previewFrame)}function previewOrbit(time){if(model||!previewOrbiting)return;const elapsed=time-previewStarted;yaw=VIEW_ANGLES.ISO[0]+elapsed*.00018;pitch=VIEW_ANGLES.ISO[1];viewQuaternion=quaternionFromViewAngles(yaw,pitch);render();previewFrame=requestAnimationFrame(previewOrbit)}
function cancelViewTransition(){if(!viewTransition)return;if(viewTransitionFrame)cancelAnimationFrame(viewTransitionFrame);viewTransition=null;viewTransitionFrame=null}function animateViewTransition(time){if(!viewTransition)return;const amount=Math.min(1,(time-viewTransition.start)/VIEW_TRANSITION_MS);viewTransition.matrix=interpolateMatrices(viewTransition.from,viewTransition.to,amount);render();if(amount<1)viewTransitionFrame=requestAnimationFrame(animateViewTransition);else{viewTransition=null;viewTransitionFrame=null;render()}}
function fit(){distance=2.1;pan=[0,0];requestAnimationFrame(render)}function setView(name){stopPreviewOrbit();const from=new Float32Array(viewRotation());cancelViewTransition();[yaw,pitch]=VIEW_ANGLES[name];viewQuaternion=quaternionFromViewAngles(yaw,pitch);viewTransition={from,to:quaternionToMatrix(viewQuaternion),matrix:from,start:performance.now()};document.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===name));viewTransitionFrame=requestAnimationFrame(animateViewTransition)}document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>setView(button.dataset.view));$('fit-view').onclick=fit;

const dropZone=$('drop-zone'),input=$('file-input'),choose=()=>{if(!activeLoad)input.click()};dropZone.onclick=choose;dropZone.onkeydown=event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();choose()}};input.onchange=()=>{openFile(input.files[0]);input.value=''};function hasFiles(event){return Array.from(event.dataTransfer?.types||[]).includes('Files')}
addEventListener('dragenter',event=>{if(!hasFiles(event))return;event.preventDefault();dragDepth++;dropOverlay.classList.add('visible');dropOverlay.setAttribute('aria-hidden','false')});addEventListener('dragover',event=>{if(hasFiles(event))event.preventDefault()});addEventListener('dragleave',event=>{if(!hasFiles(event))return;event.preventDefault();dragDepth=Math.max(0,dragDepth-1);if(!dragDepth){dropOverlay.classList.remove('visible');dropOverlay.setAttribute('aria-hidden','true')}});addEventListener('drop',event=>{event.preventDefault();dragDepth=0;dropOverlay.classList.remove('visible');dropOverlay.setAttribute('aria-hidden','true');if(event.dataTransfer.files.length)openFile(event.dataTransfer.files[0])});$('cancel-load').onclick=cancelLoad;
const VIEW_KEYS={w:'+Z',s:'-Z',a:'-X',d:'+X',q:'-Y',e:'+Y'};addEventListener('keydown',event=>{if(event.key==='Escape'&&activeLoad){event.preventDefault();cancelLoad();return}if(activeLoad||event.ctrlKey||event.metaKey||event.altKey||/^(INPUT|BUTTON)$/.test(event.target.tagName))return;const view=VIEW_KEYS[event.key.toLowerCase()];if(view){event.preventDefault();setView(view)}});
function constrainCamera(){const panLength=Math.hypot(...pan),maxPan=CAMERA_LIMIT-.25;if(panLength>maxPan)pan=pan.map(value=>value*maxPan/panLength);distance=Math.max(.15,Math.min(Math.sqrt(Math.max(.15,CAMERA_LIMIT**2-Math.hypot(...pan)**2)),distance))}function beginViewportInteraction(){stopPreviewOrbit();cancelViewTransition()}
canvas.onpointerdown=event=>{event.preventDefault();beginViewportInteraction();drag=event.button;last=[event.clientX,event.clientY];document.body.classList.add('viewport-dragging');if(drag===0&&$('trackball-rotation').checked){arcballStart=projectToTrackball(event.clientX,event.clientY,canvas.getBoundingClientRect());arcballBase=viewQuaternion}canvas.setPointerCapture(event.pointerId)};canvas.onpointerup=()=>{drag=null;arcballStart=null;arcballBase=null;document.body.classList.remove('viewport-dragging')};canvas.onpointercancel=canvas.onpointerup;
canvas.onpointermove=event=>{if(drag===null)return;event.preventDefault();const dx=event.clientX-last[0],dy=event.clientY-last[1];last=[event.clientX,event.clientY];if(drag===0){if($('trackball-rotation').checked){const current=projectToTrackball(event.clientX,event.clientY,canvas.getBoundingClientRect());viewQuaternion=multiplyQuaternions(quaternionBetweenVectors(arcballStart,current),arcballBase)}else{yaw+=dx*.008;pitch=Math.max(-1.55,Math.min(1.55,pitch+dy*.008));viewQuaternion=quaternionFromViewAngles(yaw,pitch)}}else if(drag===2){pan[0]+=dx/canvas.clientHeight*distance;pan[1]-=dy/canvas.clientHeight*distance;constrainCamera()}render()};canvas.oncontextmenu=event=>event.preventDefault();canvas.ondragstart=event=>event.preventDefault();canvas.onselectstart=event=>event.preventDefault();canvas.onwheel=event=>{event.preventDefault();beginViewportInteraction();distance*=Math.exp(event.deltaY*.001);constrainCamera();render()};
$('point-size').oninput=event=>{$('point-size-value').value=`${event.target.value} px`;render()};$('point-limit').oninput=event=>$('point-limit-value').value=Number(event.target.value).toLocaleString();$('point-limit').onchange=rebuild;for(const id of['show-mesh','show-wireframe','show-points','show-grid','show-bbox','edge-enhancement'])$(id).onchange=render;$('trackball-rotation').onchange=event=>{beginViewportInteraction();if(event.target.checked)viewQuaternion=quaternionFromViewAngles(yaw,pitch);else[yaw,pitch]=viewAnglesFromQuaternion(viewQuaternion);render()};$('mesh-opacity').oninput=event=>{$('mesh-opacity-value').value=`${event.target.value}%`;render()};$('theme').onclick=()=>{light=!light;document.body.classList.toggle('light',light);render()};addEventListener('resize',render);
let axisTargets=[];function drawAxis(){const axis=$('axis'),context=axis.getContext('2d'),width=axis.width,height=axis.height,rotation=viewRotation();context.clearRect(0,0,width,height);const rotate=([x,y,z])=>[rotation[0]*x+rotation[4]*y+rotation[8]*z,rotation[1]*x+rotation[5]*y+rotation[9]*z,rotation[2]*x+rotation[6]*y+rotation[10]*z],axes=[[[1,0,0],'#ef5350','X','+X'],[[0,0,-1],'#66bb6a','Y','+Y'],[[0,1,0],'#42a5f5','Z','+Z']].map(([vector,color,label,view])=>[rotate(vector),color,label,view]).sort((a,b)=>a[0][2]-b[0][2]);axisTargets=[];context.lineWidth=3;context.font='bold 13px "Noto Sans",system-ui';context.textAlign='center';context.textBaseline='middle';for(const[vector,color,label,view]of axes){const endX=width/2+vector[0]*34,endY=height/2-vector[1]*34;axisTargets.push({x:endX,y:endY,view});context.strokeStyle=color;context.fillStyle=color;context.beginPath();context.moveTo(width/2,height/2);context.lineTo(endX,endY);context.stroke();context.beginPath();context.arc(endX,endY,10,0,Math.PI*2);context.fill();context.fillStyle='#fff';context.fillText(label,endX,endY)}}const axisCanvas=$('axis');axisCanvas.onclick=event=>{if(activeLoad)return;const rect=axisCanvas.getBoundingClientRect(),scaleX=axisCanvas.width/rect.width,scaleY=axisCanvas.height/rect.height,x=(event.clientX-rect.left)*scaleX,y=(event.clientY-rect.top)*scaleY,target=axisTargets.reduce((best,item)=>Math.hypot(item.x-x,item.y-y)<Math.hypot(best.x-x,best.y-y)?item:best,axisTargets[0]);if(target&&Math.hypot(target.x-x,target.y-y)<=18)setView(target.view)};
render();previewFrame=requestAnimationFrame(previewOrbit);
